version: "3"

tasks:
  build:
    cmds:
      - go build -o ./dist/shareit ./app

  run:
    deps: [build]
    cmds:
      - ./dist/shareit

  watch:
    aliases: [debug]
    cmds:
      - go run github.com/mitranim/gow@latest run ./app

  ko_build:
    env:
      KO_DOCKER_REPO: registry.digitalocean.com/clockwork-registry/shareit
    cmds:
      - ko build -B ./app

  docker_build:
    cmds:
      - docker build . -t shareit:latest

  docker_run:
    deps: [docker_build]
    cmds:
      - docker run -p 8080:8080 shareit:latest
